#
# Makefile for development
#

PY_SRC_PATH=$(HOME)/projects/rasmus/python
SPIMAP_SRC_PATH=$(HOME)/projects/spimap/python/

RASMUS_SRC_FILES = __init__ \
                   linked_list \
                   plotting \
                   tablelib \
                   timer \
                   treelib \
                   treelib_parser \
                   treelib_lex \
                   treelib_tab \
	           textdraw \
                   stats \
                   svg \
                   symbolic \
                   util 

COMPBIO_SRC_FILES = __init__ \
                    birthdeath \
		    coal \
                    fasta \
                    phylo \
                    seqlib

SPIMAP_SRC_FILES = __init__ \
                   ctypes_export \
                   topology_prior

# copy subset of python modules for packaging with spidir
includepy:
	mkdir -p dlcoal/deps/rasmus
	touch dlcoal/deps/__init__.py
	for mod in $(RASMUS_SRC_FILES); do \
		cp $(PY_SRC_PATH)/rasmus/$${mod}.py dlcoal/deps/rasmus/; \
	done

	mkdir -p dlcoal/deps/compbio
	for mod in $(COMPBIO_SRC_FILES); do \
		cp $(PY_SRC_PATH)/compbio/$${mod}.py dlcoal/deps/compbio/; \
	done

	mkdir -p dlcoal/deps/spidir
	for mod in $(SPIMAP_SRC_FILES); do \
		cp $(SPIMAP_SRC_PATH)/spidir/$${mod}.py dlcoal/deps/spidir/; \
	done
